### ISSUE TITLE
Suggestion (SRS): Add more NFRs for understandablility

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#13]
Currently your NFR for the Understandable quality focuses on the understandability of the code.
![image](https://user-images.githubusercontent.com/11723492/66653725-ac870700-ec06-11e9-9b61-f5e2b866118b.png)

I think it would be good to talk about the understandability (or more specifically ease of use) of the system for your case.

I'd suggest adding something that tries to measure how long it takes for the user to set up the initial conditions of the system. (e.g. Ease of Use: The user should be able to perform the initial system set up in under MIN_SETUP_TIME.)

**Comment by sharyuwu** [comment]
@sorainsm  Thank you for pointing this out.
Yes, I agree that this system should focus more on the users' capability. Indeed, the users of this software aim to be people who only have basic knowledge of technology.
I have changed the "Understandable" in the NFR section, but instead of using the time for setting up the system, I will try to record the step users need to get the result.

See the changed link in Link: https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL1156

Please let me know your opinion on the change!

**Comment by smiths** [comment]
@sorainsm and @sharyuwu, I agree that usability should be something that this project focuses on.  The physics is fairly straightforward and the implementation shouldn't be too bad.  Focusing in usability will provide something to ensure that the project is ambitious enough.

Rather than understandability, I think you should discuss usability.  Understandability is more a quality for the code and documentation.  (Also important, but we'll be focusing on that as part of the course anyway.)

Getting the results in five steps is measurable, but the requirement about easily understandable is ambiguous.  We will be expanding verification of usability in the VnV report.  My guess is that a user survey will be part of the verification.  Rather than determine the details now, I'm okay if your NFR for usability points to a requirement to satisfy the usability measurement/verification steps outlined in the VnV plan.

**Comment by sharyuwu** [comment]
The new content of understandability please see below.
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/docs/SRS/SRS.tex#L1520
