### ISSUE TITLE
Update the first version of Problem Statement

### ISSUE THREAD

**Issue by sharyuwu** [sharyuwu/optimum-tilt-of-solar-panels#2]
@smiths  Hi Doctor Smith,
Here is the link to Problem Statement.

https://github.com/sharyuwu/optimum-tilt-of-solar-panels/blob/master/Doc/docs/ProblemStatement/ProblemStatement.pdf

Please let me know your thoughts about it.

When I wrote the "Problem." part of my problem statement, I felt there was some information missing. The main goal of this project is gaining optimum energy during seasons. Therefore, I put why we have to get more energy in the first part, and then how to get more energy in the second part.

 In the purpose of enhancing the importance of this project, I started to compare my project with other similar projects. I felt that I am working in the wrong direction. Maybe I should think more from a software engineer's aspect instead of a user's aspect?

**Comment by smiths** [comment]
Hello @sharyuwu.  Your problem statement is a good start, but I would like some changes before we officially approve it.  Can you please do the following:

- give your project a title (in the title of the document)
- change your proposed solution to be more about a user exploring the options for optimum panel tilt.  Calculating the optimum angle for each season could be one output, but I think you will want other outputs.  I think you also want to be able to compare options.  It would  be interesting to know how the optimum angle for a season compares to continual control of the solar panel so that it is always at the optimum angle.  It would also be nice to have the option of comparing other options to the option of not changing the angle at all.  I think of what you are doing as building a tool that would let people investigate the tradeoffs of different tilt angle control choices.
- for your environment, I would also like a Mac option, so that I can run your software (You should be aiming for a simple application, so it should not be difficult to make it portable.)

**Comment by sharyuwu** [comment]
Hi Docter Smith,
@smiths 
Thank you for your advice.

I agree with you that I will have to put more output to this program.

I have modified my Problem Solution and match it with my Problem Statement.

Here is the link of the historical changes of the document.
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/246638bbc8dcdedd7467ea2ea93aa230d4184a1f#diff-b4b8b1a0edb145f5ec5c97fb7ee2d5d8

**Comment by smiths** [comment]
@sharyuwu, thank you for updating your problem statement.  I approve it for your project.  However, as we work on your SRS, I think we will refine your requirements.  It seems very prescriptive the way it is written, but I think you really want a tool that lets someone explore different options.  You'll want to have requirements related to comparing different tilt angle scenarios.  You'll also want to have outputs related to the estimate of the energy produced.  What you have is good start.
