### ISSUE TITLE
References not in standard form(#5)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [sharyuwu/optimum-tilt-of-solar-panels#20]
Hi Sharon, 

I think it will be better to number the references like: 
<img width="336" alt="Screen Shot 2019-10-12 at 5 16 57 PM" src="https://user-images.githubusercontent.com/55267358/66707992-9b79eb00-ed17-11e9-8699-152b8546034d.png">

Just to standardize it.

**Comment by sharyuwu** [comment]
@best-zhang-zhi Thanks for pointing this out, but I am using the default reference style of the SRS template.
@smiths  Should I change the style of the references?

**Comment by sharyuwu** [comment]
@best-zhang-zhi  Thank you again for pointing out this issue.
You are right after standardized the reference page does make the cross-reference more clear.

See the changed line.
https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/182802b7523e22627a83680dd64e86f172a528ba#diff-8111704a3cf481beeb1db94762a8804dL21-R23

**Comment by smiths** [comment]
@sharyuwu, the reference style was fine the first way, but it is also fine with the new way.  As long as there are references and they are cited correctly, I'm fine with whatever standard is adopted.  BibTeX takes care of things quite well.  Personally I like the natbib style (author year style) because it shows me right in the text what the reference is.
