### ISSUE TITLE
SRS Review: Missing References

### ISSUE THREAD

**Issue by sorainsm** [sharyuwu/optimum-tilt-of-solar-panels#6]
If you have a reference where you got this number from it should be cited here.

![image](https://user-images.githubusercontent.com/11723492/66617188-17522700-eba2-11e9-91e0-70bf19370377.png)

**Comment by sorainsm** [comment]
Reference missing in GDD section.

![image](https://user-images.githubusercontent.com/11723492/66618330-bd079500-eba6-11e9-8a80-83f52fea7766.png)

**Comment by sharyuwu** [comment]
@sorainsm  Thanks for pointing this out.
I agree with the missing cite of the second post issue and it will be corrected.
About the first post issue, I am not sure whether or not should I cite it.
Because after I did some research, I found out the approximately " solar intensity = 1.35kw" is more like a general fact in celestial mechanics.  
Like the attacked resource, it just used the value of  " solar intensity = 1.35kw" like gravity = 9.8.
![1570764522657](https://user-images.githubusercontent.com/55363335/66622654-85a0e480-ebb6-11e9-8cc5-d2f01789da8a.jpg)

But I feel I should put is value in the section of "Values of Auxiliary Constants."
Please let me know your opinion!

**Comment by sorainsm** [comment]
@sharyuwu I definitely agree that it should go in the **Values of Auxiliary Constants**!

**Comment by sharyuwu** [comment]
@sorainsm Thanks again for posting this issue.
As the discussion, I have put this value to the Values of Auxiliary Constants and also referred it to the Assumption.

See the changed line in Link: https://github.com/sharyuwu/optimum-tilt-of-solar-panels/commit/f4ed4fbf5069cc56553eaaf82d29dd2f47ce6493#diff-8111704a3cf481beeb1db94762a8804dL1312-R1388
